global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    static_configs:
      - targets:
          - 'ipNodo:9100'  # 
          - 'ipNodo:9100'  # 

  - job_name: 'wordpress_prompress'
    metrics_path: /wp-json/prompress/v1/metrics
    static_configs:
      - targets:
          - 'ipNodo:80'  # WordPress
